PARENT_FOLDER_ID = "1lsky0585MIO6iuZGv1jYU0ccHpArNVR8"
GOOGLE_CLIENT_ID = "569574300258-c2dugf6qmpjprio1d9qiliadhk8m3duq.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GOOGLE_REFRESH_TOKEN = "1//01WAvweNiXLNQCgYIARAAGAESNwF-L9IrdG3d8qz5Y5Ip52eBo4g0KUtRkJQUI3di0utAkJwLXcOfHKM7UyuIsyLv44ccRJ8vhwQ"
Maps_API_KEY = "AIzaSyBDLtfZAtVWFtUJsimc8QL987rxv6aEf0o"